config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'pages#home', as: 'home'
  get 'profile', to: 'pages#profile'

  devise_for :users

  resources :trips, except: [:show] do
    resources :days, only: [ :new, :create ]
  end

  resources :days, only: [ :destroy ]


  resources :places, only: [ :new, :create, :destroy]

  resources :vehicles, only: [ :new, :create, :edit]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/trip.rb
require "open-uri"
require "json"

class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  belongs_to :end_place, class_name: "Place"
  belongs_to :start_place, class_name: "Place"
  before_save :calculate_distance

  has_many :days, dependent: :destroy
  accepts_nested_attributes_for :days, allow_destroy: true

  validates  :label, :vehicle, presence: true

  attr_accessor :schedule

  def calculate_distance
    if self.vehicle.vehicle_type == "metro"
      self.distance = Geocoder::Calculations.distance_between([self.start_place.latitude,self.start_place.longitude],[self.end_place.latitude,self.end_place.longitude])
    else
      if self.vehicle.vehicle_type == "car" || self.vehicle.vehicle_type == "bus"
        profile = "mapbox/driving"
      elsif self.vehicle.vehicle_type == "bike"
        profile = "mapbox/cycling"
      elsif self.vehicle.vehicle_type == "walk"
        profile = "mapbox/walking"
      end
      coordinates = "#{self.start_place.longitude},#{self.start_place.latitude};#{self.end_place.longitude},#{self.end_place.latitude}"
      url = "https://api.mapbox.com/directions/v5/#{profile}/#{coordinates}?access_token=#{ENV["MAPBOX_API_KEY"]}&geometries=geojson"
      distance_serialized = URI.open(url).read
      distance = JSON.parse(distance_serialized)
      self.distance = distance["routes"][0]["distance"]/1000
    end
    self.distance = self.distance * 2 if self.round
  end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:edit, :update, :destroy]
  before_action :week_days, only: [:new, :edit, :index]

  def index
    @trips = Trip.where(user_id: current_user.id).order(updated_at: :desc)
  end

  def new
    @places = Place.where(user_id: current_user.id)
    @trip = Trip.new
    @trip.days.build
    @vehicles = Vehicle.where(user_id: current_user.id)
  end

  def create
    @places = Place.where(user_id: current_user.id)
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id

    start_place = Place.find(params[:trip][:start_place_id])
    end_place = Place.find(params[:trip][:end_place_id])

    @trip.start_place = start_place
    @trip.end_place = end_place
    @trip.label = "#{start_place.name} to #{end_place.name}"

    if @trip.save
      if params[:trip][:schedule].present? && params[:trip][:schedule].values.any?
        params[:trip][:schedule].values.each { |day| Day.create(date: Date.parse(day), trip: @trip) }
        calculate_score(@trip)
        redirect_to trips_path
      else
        flash[:error] = "Please select at least one day."
        redirect_to new_trip_path
      end
    else
      @vehicles = Vehicle.where(user_id: current_user.id)
      flash.now[:error] = "Please select at least one day." # Définir le message d'erreur pour la nouvelle tentative
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @places = Place.where(user_id: current_user.id)
    @vehicles = Vehicle.where(user_id: current_user.id)
    @trip_day_dates = @trip.days.pluck(:date)
  end

  def update
    @places = Place.where(user_id: current_user.id)
    @vehicles = Vehicle.where(user_id: current_user.id)

    start_place = Place.find(params[:trip][:start_place_id])
    end_place = Place.find(params[:trip][:end_place_id])

    @trip.start_place = start_place
    @trip.end_place = end_place

    if @trip.update(trip_params)
      @trip.days.destroy_all
      params[:trip][:schedule].values.each do |day|
        Day.create(date: Date.parse(day), trip: @trip)
      end
      @trip.label = "#{start_place.name} to #{end_place.name}"
      calculate_score(@trip)
      @trip.save
      redirect_to trips_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:label, :start_place_id, :end_place_id, :vehicle_id, :round, schedule: [])
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def week_days
    @week_days = []
    date  = Date.parse("Monday")
    delta = date > Date.today ? 0 : 7
    date += delta
    7.times do |i|
      @week_days << [(date + i).strftime("%A"), (date + i)]
    end
  end

  def calculate_score(trip_instance)
    if trip_instance.vehicle.vehicle_type == "car"
      @calculate_score = (trip_instance.vehicle.carbon_kg/100.to_f) * trip_instance.distance * trip_instance.days.count
    elsif trip_instance.vehicle.vehicle_type == "bus"
      @calculate_score = 0.079 * trip_instance.distance * trip_instance.days.count
    elsif trip_instance.vehicle.vehicle_type == "metro"
      @calculate_score = 0.028 * trip_instance.distance * trip_instance.days.count
    elsif trip_instance.vehicle.vehicle_type == "bike" || trip_instance.vehicle.vehicle_type == "walking"
      @calculate_score = 0
    end
    trip_instance.score = @calculate_score
    trip_instance.save
  end

end

app/views/trips/edit.html.erb
<h1 class="add-trip-title">Edit Trip</h1>

<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="container-dark-blue" data-controller="checkall">
  <div class="container-inside">

    <div class="trip-banner">
      <div class="trip-banner-2">
        <h2>My Trips</h2>
        <%= image_tag("Vector.png", alt: "Logo", class: "logo-trip") %>
      </div>
    </div>

    <%= simple_form_for(@trip) do |f| %>
      <%= f.hidden_field :label %>
      <%= f.input :start_place_id, collection: @places.map { |p| [p.name, p.id] }, prompt: 'Select a start place' %>
      <%= f.input :end_place_id, collection: @places.map { |p| [p.name, p.id] }, prompt: 'Select an end place' %>
      <%= f.input :vehicle_id, collection: @vehicles.map { |v| [v.vehicle_type, v.id] }, prompt: 'Select a vehicle' %>
      <div class="container-edit-trip">
        <p class="select-frequency">Select Frequency</p>
        <div class="container-checkbox-all">
          <div class="input-check-all">
            <input type="checkbox" id="check-all" class="input-check-all-buton form-check-input is-valid boolean optional" name="check-all" data-action="change->checkall#allchecked">
            <label for="input-all" class="form-check-label boolean optional">Check all</label>
          </div>
        </div>
        <div class="days-section d-flex">
          <% @week_days.each do |day_name, date| %>
            <div class="day-checkbox">
              <%= check_box_tag "trip[schedule][#{date}]", date, @trip_day_dates.include?(date),
                                class: "form_input", data: { check_all_target: "dayCheckbox" },
                                data: { target: "checkall.dayCheckbox" } %>
              <%= label_tag "trip_schedule_#{date}", class: 'form_label_trip' do %>
                <%= day_name[0, 2] %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="container-checkbox-all">
          <div class="checkboxes-roundTrip">
            <%= f.input :round, label: "Round Trip ?", input_html: { class: "form-check-input is-valid boolean optional" } %>
          </div>
        </div>
      </div>

      <%= f.submit "Edit Trip", class: "button-green button-create-trip button-green-create" %>

      <%= link_to "cancel", trips_path, class: "button-cancel" %>
    <% end %>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container">
  <h1 class="main-title">My trips</h1>

  <% @trips.each do |trip| %>
    <div class="container-trip">
      <div class="container-inside">
        <div class="trip-front-part">
          <div class="trip-name">
              <%= trip.start_place.name %>

                <% if trip.round %>
                  <div class="round-trip">
                    <i class="fa-solid fa-arrow-right"></i>
                    <i class="fa-solid fa-arrow-left"></i>
                  </div>
                <% else %>
                  <i class="fa-solid fa-arrow-right"></i>
                <% end %>

              <%= trip.end_place.name %>
            <br>
          </div>

          <div class="logo-trash-pencil">
            <%= link_to edit_trip_path(trip) do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>
            <%= link_to trip_path(trip), data: { turbo_method: :delete, confirm: 'Are you sure?' } do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </div>
        </div>

        <div class="index-logo d-flex">
              <% case trip.vehicle.vehicle_type %>
                <% when "car" %>
                  <i class="fa-solid fa-car"></i>
                <% when "bus" %>
                  <i class="fa-solid fa-bus"></i>
                <% when "bike" %>
                  <i class="fa-solid fa-bicycle"></i>
                <% when "walk" %>
                  <i class="fa-solid fa-person-walking"></i>
                <% when "metro" %>
                  <i class="fa-solid fa-train"></i>
                <% else %>
                  <i class="fa-solid fa-question"></i>
              <% end %>
              <% if trip.score < 10 %>
                <p class="text-good"> <%= sprintf('%.1f', trip.score)%> kg/CO2 </p>
              <% elsif trip.score < 20 && trip.score > 10 %>
                <p class="text-average"> <%= sprintf('%.1f', trip.score)%> kg/CO2 </p>
              <% elsif trip.score > 20 %>
                <p class="text-bad"> <%= sprintf('%.1f', trip.score)%> kg/CO2 </p>
              <% end %>
            </div>
      </div>

      <div class="container-edit-trip">
        <div class="days-section d-flex w-100">
            <% @trip_day_dates = trip.days.pluck(:date) %>
            <% @week_days.each do |day_name, date| %>
              <div class="day-checkbox">
                <%= check_box_tag "trip[schedule][]", date, @trip_day_dates.include?(date), class: "form_input" %>
                <%= label_tag "trip", class: 'form_label_trip' do %>
                  <%= day_name[0, 2] %>
                <% end %>
              </div>
            <% end %>
          </div>
      </div>
    </div>

    <% end %>
    <div class='add-button-container'>
      <%= link_to new_trip_path, class: "add-trip-button" do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
  </div>

  <div class="hidden-container">

  </div>

  <%= link_to "See my score", profile_path, class: "button-green button-trip-index secondary title" %>
</div>

app/views/trips/new.html.erb
<h1 class="add-trip-title">Add trip</h1>

<% if flash[:error].present? %>
  <div class="alert alert-danger alert-new-trip">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="container-dark-blue" data-controller="checkall">
  <div class="container-inside">

    <div class="trip-banner">
      <div class="trip-banner-2">
        <h2>My trips</h2>
        <%= image_tag("Vector.png", alt: "Logo", class: "logo-trip") %>
      </div>
    </div>

    <%= simple_form_for(@trip) do |f| %>
      <%= f.hidden_field :label %>
      <%= f.input :start_place_id, collection: @places.map { |p| [p.name, p.id] }, prompt: 'Select a start place' %>
      <%= f.input :end_place_id, collection: @places.map { |p| [p.name, p.id] }, prompt: 'Select an end place' %>
      <%= f.input :vehicle_id, collection: @vehicles.map { |v| [v.vehicle_type, v.id] }, prompt: 'Select a vehicle' %>
      <div class="container-edit-trip">
        <p class="select-frequency">Select Frequency</p>
        <div class="container-checkbox-all">
          <div class="input-check-all">
            <input type="checkbox" id="check-all" class="input-check-all-buton form-check-input is-valid boolean optional" name="check-all" data-action="change->checkall#allchecked">
            <label for="input-all" class="form-check-label boolean optional">Check all</label>
          </div>
        </div>
        <div class="days-section d-flex">
          <% @week_days.each do |day_name, date| %>
            <div class="day-checkbox">
              <%= check_box_tag "trip[schedule][#{date}]", date, false,
                                class: "form_input", data: { check_all_target: "dayCheckbox" },
                                data: { target: "checkall.dayCheckbox" } %>
              <%= label_tag "trip_schedule_#{date}", class: 'form_label_trip' do %>
                <%= day_name[0, 2] %>
              <% end %>
            </div>
          <% end %>
        </div>
         <div class="container-checkbox-all">
          <div class="checkboxes-roundTrip">
            <%= f.input :round, label: "Round Trip ?", input_html: { class: "form-check-input is-valid boolean optional" } %>
          </div>
        </div>
      </div>

      <%= f.submit "Add trip", class: "button-green button-create-trip button-green-create"  %>

      <%= link_to "cancel", trips_path, class: "button-canceltrip"%>

    <% end %>

  </div>
</div>