config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'pages#home', as: 'home'
  get 'profile', to: 'pages#profile'

  devise_for :users

  resources :trips, except: [:show] do
    resources :days, only: [ :new, :create ]
  end

  resources :days, only: [ :destroy ]


  resources :places, only: [ :new, :create, :destroy]

  resources :vehicles, only: [ :new, :create, :edit]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/home.html.erb
<div class= "logo">
<%= image_tag 'logo.png', alt: "Logo Ecotrack" %>
</div>
<p class="secondary-title home-sentence">Estimate your carbon print <br> based on your weekly trips</p>
<% if current_user.trips.any?%>
  <%= link_to "See my score", new_place_path, class:"button-home" %>
<% else %>
  <%= link_to "Get started", new_place_path, class:"button-home" %>
<% end %>

app/views/pages/profile.html.erb
<h1 class="main-title">My Ecotracker's Score</h1>
<h3 class="secondary-title">Based on my weekly trip</h3>



<div class="page">

<div class="container-score">
  <% if @score == 0 %>

        <div class="logo">
          <%= image_tag "arcticons_earth.svg" %>
        </div>
        <h2>No score yet !</h2>


    <% elsif  @score > 15%>
      <i class="fa-solid fa-share-nodes fs-3 shared-logo"
        data-controller="share-button"
        data-action="click->share-button#fire"
        data-share-content-title-value="My EcoScore"
        data-share-content-text-value="+18$ saved on fuel consumption this week"
        data-share-content-url-value="<%= profile_url %>"
      >
      </i>
        <div class="logo-smile">
          <i class="fa-regular fa-face-grin-beam-sweat"></i>
        </div>
        <div class="jauge">
          <div class="avancement" style= "right: <%= @placement %>%;"></div>
        </div>
        <h3><strong><%= sprintf('%.1f', @score) %> Kg</strong></h3><p>CO2 / week</p>
        <div class="container-message">
          <i class="fa-solid fa-tree fa-2x"></i>
          <h3>50</h3><p>trees saved with <strong>10km</strong> less by weeks</p>
        </div>
         <div class="container-message">
          <i class="fa-solid fa-earth-americas fa-2x"></i>
          <h3> 3.5</h3><p>planets needed if everybody have your consumption</p>
        </div>


    <%  elsif @score < 15 %>
          <i class="fa-solid fa-share-nodes fs-3 shared-logo"
            data-controller="share-button"
            data-action="click->share-button#fire"
            data-share-content-title-value="My EcoScore"
            data-share-content-text-value="+18$ saved on fuel consumption this week"
            data-share-content-url-value="<%= profile_url %>"
          >
          </i>
        <div class="logo-smile">
          <i class="fa-regular fa-face-smile"></i>
        </div>
        <div class="jauge">
          <div class="avancement" style= "right: <%= @placement %>%;"></div>
        </div>
        <h3><strong><%= sprintf('%.1f', @score) %> Kg</strong></h3><p>CO2 / week</p>
        <div class="container-message">
          <i class="fa-solid fa-chart-simple fa-2x"></i>
          <h3>13</h3><p>kg of CO2 less than last week</p>
        </div>
        <div class="container-message">
          <i class="fa-solid fa-thumbs-up fa-2x"></i>
          <h3>92%</h3><p>better than the population</p>
        </div>
        <div class="container-message">
          <i class="fa-solid fa-dollar-sign fa-2x"></i>
          <h3>18</h3><p>saved on fuel budget this week</p>

        </div>

      <%end %>
    </div>

    <div class="bottom-button">
      <% if @score == 0 %>
          <%= link_to "Plan my first trip ", new_trip_path, class: "button-green green-score"  %>
        <% elsif @score > 0 %>
          <%= link_to "Edit my trips ", trips_path, class: "button-green green-score"  %>
      <%end %>
    </div>


    </div>