config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'pages#home', as: 'home'
  get 'profile', to: 'pages#profile'

  devise_for :users

  resources :trips, except: [:show] do
    resources :days, only: [ :new, :create ]
  end

  resources :days, only: [ :destroy ]


  resources :places, only: [ :new, :create, :destroy]

  resources :vehicles, only: [ :new, :create, :edit]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user

  has_many :start_trips, class_name: 'Trip', foreign_key: 'start_place_id'
  has_many :end_trips, class_name: 'Trip', foreign_key: 'end_place_id'

  validates :name, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController


  def index
    @places = Place.all

  end

  def new
    @places = Place.where(user: current_user)
    @place = Place.new
  end

  def create
    @places = Place.all
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to new_place_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to new_place_path


  end


  end

  private

  def place_params
    params.require(:place).permit(:address, :name)
  end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>

  <%= f.input :name, input_html: { placeholder: 'Ex: Home, Work, Gym, etc..', class: "custom-placeholder" }%>

  <%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>

  <%= f.submit "Add your place", class: "button-empty-green" %>

<% end %>

app/views/places/new.html.erb
  <div class="container-dark-blue">
  <div class="progress-container">
    <div class="progression-bar-full">
      <div class= "icon-home">
        <i class="fa-solid fa-house home-logo-place"></i>
      </div>
    </div><div class="progression-bar"></div>
  </div>
    <h2 class="secondary-title">Enter the name of your locations of the week</h2>
    <div class="container-inside">
        <% if params[:empty_place] %>
          <p class="error-message">the user must have at least one registered place</p>
        <% end %>
        <%= render 'form', new: @place %>

          <div class="scroller">
            <div class="all-places">
              <% @places.reverse_each do |place| %>
                <div class="places">
                  <%= link_to place_path(place), class: 'place-link', data: { turbo_method: :delete, confirm: 'Are you sure?' }  do %>
                    <div class="place">
                      <p class="name-place"><%= place.name %></p>
                      <i class="fa-solid fa-trash-can"></i>
                    </div>
                  <% end %>
                </div>
              <% end %>
        </div>
      </div>
    </div>
    <%= link_to "Next", new_vehicle_path, class: "button-green secondary-title"  %>
  </div>