config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'pages#home', as: 'home'
  get 'profile', to: 'pages#profile'

  devise_for :users

  resources :trips, except: [:show] do
    resources :days, only: [ :new, :create ]
  end

  resources :days, only: [ :destroy ]


  resources :places, only: [ :new, :create, :destroy]

  resources :vehicles, only: [ :new, :create, :edit]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <!--<!– Facebook Open Graph data –>-->
    <meta property=”og:title” content="<%= meta_title %>" />
    <meta property=”og:type” content="website" />
    <meta property=”og:url” content="<%= request.original_url %>" />
    <meta property=”og:image” content="<%= meta_image %>" />
    <meta property=”og:description” content="<%= meta_description %>" />
    <meta property=”og:site_name” content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">

    <meta name="theme-color" content="#ffffff">

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= javascript_importmap_tags %>
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>



    <div class="container-layout">

      <div class="navbar-ecotrack">
        <div class="navbar navbar-light navbar-lewagon">
            <div class="container-fluid">
                <div class="d-flex justify-content-between w-100">
                    <div class="ecotrackw d-flex justify-content-between">
                        <div class="logo_bar">
                            <%= image_tag 'crop_logo.png', alt: "Logo Ecotrack", class: "logo_navbar" %>
                        </div>
                        <a href="<%= home_path %>">
                          <div class="title_bar">
                              <h3>EcoTracker</h3>
                          </div>
                        </a>
                    </div>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                        <span class="navbar-toggler-icon">
                            <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
                        </span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item <%= 'active' if current_page?(trips_path) %>">
                          <% unless current_page?(trips_path) %>
                            <%= link_to "My Ecotracker's trips", trips_path, class: 'nav-link' %>
                          <%end%>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(profile_path) %>">
                          <% unless current_page?(profile_path) %>
                            <%= link_to "My Ecotracker's score", profile_path, class: 'nav-link' %>
                          <%end%>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(new_vehicle_path) %>">
                          <% unless current_page?(new_vehicle_path) %>
                            <%= link_to "Add my vehicles", new_vehicle_path, class: 'nav-link' %>
                          <%end%>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(new_place_path) %>">
                          <% unless current_page?(new_place_path) %>
                            <%= link_to "My places", new_place_path, class: 'nav-link' %>
                          <%end%>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>